// <auto-generated />
using System;
using Almirante.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Almirante.Api.Data.Migrations
{
    [DbContext(typeof(AlmiranteDbContext))]
    [Migration("20260921222826_AddEventosOperacoesResposta")]
    partial class AddEventosOperacoesResposta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Almirante.Api.Entities.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AbsoluteExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastRenewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AbsoluteExpiresAtUtc");

                    b.HasIndex("UsuarioId", "AbsoluteExpiresAtUtc");

                    b.ToTable("AuthSessions", (string)null);
                });

            modelBuilder.Entity("Almirante.Api.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .IsUnique();

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("Almirante.Api.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlimentacaoIndividual")
                        .HasColumnType("bit");

                    b.Property<decimal>("AlimentacaoValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AtualizadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataEvento")
                        .HasColumnType("date");

                    b.Property<Guid>("EventoGrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventoReferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("SeguroObrigatorio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TransporteEhGratis")
                        .HasColumnType("bit");

                    b.Property<decimal>("TransporteValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPorMembro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EventoGrupoId")
                        .HasName("AK_eventos_Id_EventoGrupoId");

                    b.HasIndex("AtualizadoPorUsuarioId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("EventoGrupoId");

                    b.HasIndex("EventoReferenciaId");

                    b.HasIndex("Ativo", "DataEvento");

                    b.ToTable("eventos", null, t =>
                        {
                            t.HasCheckConstraint("CK_eventos_grupo", "[EventoReferenciaId] IS NOT NULL OR [EventoGrupoId] = [Id]");

                            t.HasCheckConstraint("CK_eventos_valores_nao_negativos", "[TransporteValor] >= 0 AND [AlimentacaoValor] >= 0 AND [SeguroObrigatorio] >= 0 AND [ValorPorMembro] >= 0");

                            t.HasCheckConstraint("CK_eventos_valores_normalizados", "([TransporteEhGratis] = 0 OR [TransporteValor] = 0) AND ([AlimentacaoIndividual] = 0 OR [AlimentacaoValor] = 0) AND [ValorPorMembro] = [TransporteValor] + [AlimentacaoValor] + [SeguroObrigatorio]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Almirante.Api.Entities.EventoMembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DesativadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventoGrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("LancamentoId");

                    b.HasIndex("MembroId");

                    b.HasIndex("EventoGrupoId", "MembroId")
                        .IsUnique()
                        .HasDatabaseName("UX_evento_membros_grupo_membro_ativo")
                        .HasFilter("[Ativo] = 1");

                    b.HasIndex("EventoId", "EventoGrupoId");

                    b.ToTable("evento_membros", (string)null);
                });

            modelBuilder.Entity("Almirante.Api.Entities.EventoOperacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RespostaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("eventos_operacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_eventos_operacoes_RespostaJson", "[RespostaJson] IS NULL OR ISJSON([RespostaJson]) = 1");
                        });
                });

            modelBuilder.Entity("Almirante.Api.Entities.HistoricoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlimentacaoIndividual")
                        .HasColumnType("bit");

                    b.Property<decimal>("AlimentacaoValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DataEvento")
                        .HasColumnType("date");

                    b.Property<Guid>("EventoGrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventoReferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExcluidoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpResponsavel")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ParticipantesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeMembros")
                        .HasColumnType("int");

                    b.Property<decimal>("SeguroObrigatorio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TransporteEhGratis")
                        .HasColumnType("bit");

                    b.Property<decimal>("TransporteValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorPorMembro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("historico_eventos", null, t =>
                        {
                            t.HasCheckConstraint("CK_historico_eventos_ParticipantesJson", "ISJSON([ParticipantesJson]) = 1");
                        });
                });

            modelBuilder.Entity("Almirante.Api.Entities.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AtualizadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Finalidade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OperacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoFluxo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("AtualizadoPorUsuarioId");

                    b.HasIndex("EventoId");

                    b.HasIndex("Finalidade");

                    b.HasIndex("MembroId");

                    b.HasIndex("OperacaoId");

                    b.HasIndex("Status");

                    b.HasIndex("Vencimento");

                    b.ToTable("Lancamentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lancamentos_Categoria", "[Categoria] IN (0, 1)");

                            t.HasCheckConstraint("CK_Lancamentos_Status", "[Status] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Lancamentos_TipoFluxo", "[TipoFluxo] IN (0, 1)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Almirante.Api.Entities.LancamentoDeletado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacaoOriginal")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExcluidoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Finalidade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpResponsavel")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("OperacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoFluxo")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("lancamentos_deletados", null, t =>
                        {
                            t.HasCheckConstraint("CK_lancamentos_deletados_Categoria", "[Categoria] IN (0, 1)");

                            t.HasCheckConstraint("CK_lancamentos_deletados_Status", "[Status] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_lancamentos_deletados_TipoFluxo", "[TipoFluxo] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Almirante.Api.Entities.LancamentoOperacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LancamentosCriados")
                        .HasColumnType("int");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TipoFluxo")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosProcessados")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("LancamentosOperacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_LancamentosOperacoes_Categoria", "[Categoria] IN (0, 1)");

                            t.HasCheckConstraint("CK_LancamentosOperacoes_TipoFluxo", "[TipoFluxo] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Almirante.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("SessionId", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Almirante.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FalhasLoginConsecutivas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LoginBloqueadoAteUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("SecurityVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaFalhaLoginUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Almirante.Api.Entities.AuthSession", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Almirante.Api.Entities.Evento", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Almirante.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Almirante.Api.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoReferenciaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Almirante.Api.Entities.EventoMembro", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Almirante.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Almirante.Api.Entities.Evento", "Evento")
                        .WithMany("Membros")
                        .HasForeignKey("EventoId", "EventoGrupoId")
                        .HasPrincipalKey("Id", "EventoGrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Almirante.Api.Entities.EventoOperacao", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Almirante.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Almirante.Api.Entities.HistoricoEvento", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Almirante.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Almirante.Api.Entities.Lancamento", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Almirante.Api.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Almirante.Api.Entities.Usuario", "Membro")
                        .WithMany("Lancamentos")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("Almirante.Api.Entities.LancamentoDeletado", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Almirante.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Almirante.Api.Entities.LancamentoOperacao", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Almirante.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("Almirante.Api.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Almirante.Api.Entities.AuthSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Almirante.Api.Entities.Usuario", b =>
                {
                    b.HasOne("Almirante.Api.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("Almirante.Api.Entities.Evento", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("Almirante.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
